# cookie cutter git lab development pipeline
# TODO - create an image that is the openjdk image + the SDK and NDK setup to 
#        make initialization faster   shb 10/19/2019

image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "29"
  ANDROID_BUILD_TOOLS: "29.0.3"
  ANDROID_SDK_TOOLS:   "4333796"
  NDK_VERSION: "12b"
  WGET: "wget --quiet --tries=0"
  GIT_STRATEGY: clone
  GIT_TOKEN: "3ydao3HGquPdh2ybxKQk"


cache:
  key: android_sdk29_buildtools_29.0.3_ndk_12b
  paths:
    - android-sdk-linux
    - android-ndk-r12b

before_script:
  - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
  - apt-get install git-lfs

  - if [[ "$CI_COMMIT_REF_NAME" == "maintenance-"* ]]; then
        SDK_BRANCH_NAME=$CI_COMMIT_REF_NAME;
    else
        SDK_BRANCH_NAME="master";
    fi
  - echo "SDK Branch $SDK_BRANCH_NAME"

  - git clone --depth 1 -b $SDK_BRANCH_NAME https://civsdk_builder:_NxPo8NmvzvgNRxaNzH-@git.takmaps.com/sdks/atak-civ.git;
  
  # TODO - investigate why lfs pull is failing with 
  # git lfs pull cannot add to the index - missing --add option? fixed
  # when using git clone -n 
  #- pushd .
  #- cd atak-civ
  #- GIT_TRACE=1 git lfs pull -I "*main.jar"
  #- popd


  - if [ ! -d android-sdk-linux ]; then
       $WGET --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip;
       unzip -qq -d android-sdk-linux android-sdk.zip;
    else
       echo "using cached version of the the android sdk";
    fi
  - mkdir -p ~/.android;
  - touch ~/.android/repositories.cfg;
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null;
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null;
  - echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null;

  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/

  # install the NDK build so we can actually strip the libraries

  - if [ ! -d android-ndk-r12b ]; then
       $WGET --output-document=android-ndk.zip https://dl.google.com/android/repository/android-ndk-r${NDK_VERSION}-linux-x86_64.zip;
       unzip -qq  android-ndk.zip;
    else
       echo "using cached version of the the android ndk";
    fi


  # temporarily disable checking for EPIPE error and use yes to accept all licenses
  - set +o pipefail
  - yes | android-sdk-linux/tools/bin/sdkmanager --licenses
  - set -o pipefail
  - export ANDROID_NDK_HOME=$PWD/android-ndk-r${NDK_VERSION}
  - chmod +x ./gradlew
  - git branch
  - java -version
  - ./gradlew --version

stages:
  - build
  - test
  
assembleMilSdkRelease:
  stage: build
  script:
    - pwd .
    - mkdir sdk
    - cp atak-civ/main.jar sdk
    - cp atak-civ/android_keystore sdk
    - cp atak-civ/atak-gradle-takdev.jar sdk
    - find . -name main.jar
    - ./gradlew -Pci --console=plain -Ptakdev.plugin=$PWD/sdk/atak-gradle-takdev.jar lintMilRelease assembleMilRelease
  artifacts:
    expire_in: 720h
    paths:
    - app/build/outputs/

assembleMilOdkRelease:
  stage: build
  script:
    - ./gradlew --console=plain -Pci -Ptakrepo.force=true -Ptakrepo.url=${ARTIFACTORY_URL_APK} -Ptakrepo.user=${ARTIFACTORY_USER} -Ptakrepo.password=${ARTIFACTORY_PASSWORD} assembleMilRelease
  artifacts:
    expire_in: 720h
    paths:
    - app/build/outputs/
  when: manual
  
assembleCivSdkRelease:
  stage: build
  script:
    - mkdir sdk
    - cp atak-civ/main.jar sdk
    - cp atak-civ/android_keystore sdk
    - cp atak-civ/atak-gradle-takdev.jar sdk
    - ./gradlew -Pci --console=plain -Ptakdev.plugin=$PWD/sdk/atak-gradle-takdev.jar lintCivRelease assembleCivRelease
  artifacts:
    expire_in: 720h
    paths:
    - app/build/outputs/
  when: manual

assembleCivOdkRelease:
  stage: build
  script:
    - ./gradlew --console=plain -Pci -Ptakrepo.force=true -Ptakrepo.url=${ARTIFACTORY_URL_APK} -Ptakrepo.user=${ARTIFACTORY_USER} -Ptakrepo.password=${ARTIFACTORY_PASSWORD} assembleCivRelease
  artifacts:
    expire_in: 720h
    paths:
    - app/build/outputs/
  when: manual
  
assembleFveySdkRelease:
  stage: build
  script:
    - mkdir sdk
    - cp atak-civ/main.jar sdk
    - cp atak-civ/android_keystore sdk
    - cp atak-civ/atak-gradle-takdev.jar sdk
    - ./gradlew -Pci --console=plain -Ptakdev.plugin=$PWD/sdk/atak-gradle-takdev.jar lintFveyRelease assembleFveyRelease
  artifacts:
    expire_in: 720h
    paths:
    - app/build/outputs/
  when: manual
  
assembleFveyOdkRelease:
  stage: build
  script:
    - ./gradlew --console=plain -Pci -Ptakrepo.force=true -Ptakrepo.url=${ARTIFACTORY_URL_APK} -Ptakrepo.user=${ARTIFACTORY_USER} -Ptakrepo.password=${ARTIFACTORY_PASSWORD} assembleFveyRelease
  artifacts:
    expire_in: 720h
    paths:
    - app/build/outputs/
  when: manual


testRelease:
  stage: test
  script:
    - mkdir sdk
    - cp atak-civ/main.jar sdk
    - cp atak-civ/android_keystore sdk
    - cp -R atak-civ/espresso .
    - cp atak-civ/atak-gradle-takdev.jar sdk
    - ./gradlew -Pci --console=plain -Ptakdev.plugin=$PWD/sdk/atak-gradle-takdev.jar :app:testMilRelease

